services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      # Estas variables deben coincidir con las que usará Prisma y la app
      DATABASE_URL: "postgresql://user:password@db:5432/mydb?schema=public"
      # NEXT_PUBLIC_API_URL: http://localhost:3001/api # Actualizar si es necesario
    depends_on:
      - db
    volumes:
      - .:/app # Monta el código fuente para desarrollo (hot-reloading)
      - /app/node_modules # No montar node_modules del host
      - /app/.next # No montar .next del host
    dns:
      - 8.8.8.8  # Google DNS
      - 1.1.1.1  # Cloudflare DNS

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 